language: objective-c
osx_image: xcode8.3
cache:
  - bundler
  - cocoapods


before_install:
  - bundle install
  - bundle exec pod update

script:
  - bundle exec fastlane scan "iOS Hub.xcworkspace" --scheme "iOS Hub"

after_success:
  - bash <(curl -s https://codecov.io/bash)
