language: objective-c
osx_image: xcode9.1
cache:
  - bundler
  - cocoapods

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec pod update

script:
  - bundle exec fastlane scan "iOS Hub.xcworkspace" --scheme "iOS Hub"

after_success:
  - bash <(curl -s https://codecov.io/bash)
